#-----------------------------------------------------------------------
# Macro file cosmic muon distribution from CRY
#-----------------------------------------------------------------------

#############################  G E O M E T R Y  ###################################
# WORLD
#/musr/command construct box World 500000 500000 500000 G4_AIR 0 0 0 no_logical_volume norot dead -1
/musr/command construct box World 500000 500000 500000 G4_Galactic 0 0 0 no_logical_volume norot dead -1

# (water ; mud ; concrete wall ; air)

# data point 1 : 0.70 ; 12.90 ; 4 ; 6 ; det original size 400 100 10
/musr/command construct box water1 25000 25000 6800 wangpuWater -350000 0 -6800 log_World norot dead 7001
/musr/command construct box tidal1 25000 25000 79 G4_AIR 0 0 6721 log_water1 norot dead 6001
/musr/command construct box mud1 25000 25000 6450 GrayMealySand 0 0 -350 log_water1 norot dead 8001
/musr/command construct box wall1 25000 25000 1000 Concrete -350000 0 -14600 log_World norot dead 5001
/musr/command construct box save_SciDet11 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -350000 0 -21610 log_World norot musr/ScintSD 101
/musr/command construct box save_SciDet12 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -350000 0 -21730 log_World norot musr/ScintSD 102

# data point 2 : 15.1 ; 0.54 ; 4 ; 6
/musr/command construct box water2 25000 25000 7820 wangpuWater -300000 0 -7820 log_World norot dead 7002
/musr/command construct box tidal2 25000 25000 79 G4_AIR 0 0 7741 log_water2 norot dead 6002
/musr/command construct box mud2 25000 25000 270 GrayMealySand 0 0 -7550 log_water2 norot dead 8002
/musr/command construct box wall2 25000 25000 1000 Concrete -300000 0 -16640 log_World norot dead 5002
/musr/command construct box save_SciDet21 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -300000 0 -23650 log_World norot musr/ScintSD 103
/musr/command construct box save_SciDet22 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -300000 0 -23770 log_World norot musr/ScintSD 104

# data point 3 : 15.72 ; 1.52 ; 4 ; 6
/musr/command construct box water3 25000 25000 8620 wangpuWater -250000 0 -8620 log_World norot dead 7003
/musr/command construct box tidal3 25000 25000 79 G4_AIR 0 0 8541 log_water3 norot dead 6003
/musr/command construct box mud3 25000 25000 760 GrayMealySand 0 0 -7860 log_water3 norot dead 8003
/musr/command construct box wall3 25000 25000 1000 Concrete -250000 0 -18240 log_World norot dead 5003
/musr/command construct box save_SciDet31 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -250000 0 -25240 log_World norot musr/ScintSD 105
/musr/command construct box save_SciDet32 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -250000 0 -25360 log_World norot musr/ScintSD 106

# data point 4 : 16.62 ; 2.00
/musr/command construct box water4 25000 25000 9310 wangpuWater -200000 0 -9310 log_World norot dead 7004
/musr/command construct box tidal4 25000 25000 79 G4_AIR 0 0 9231 log_water4 norot dead 6004
/musr/command construct box mud4 25000 25000 1000 GrayMealySand 0 0 -8310 log_water4 norot dead 8004
/musr/command construct box wall4 25000 25000 1000 Concrete -200000 0 -19620 log_World norot dead 5004
/musr/command construct box save_SciDet41 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -200000 0 -26630 log_World norot musr/ScintSD 107
/musr/command construct box save_SciDet42 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -200000 0 -26750 log_World norot musr/ScintSD 108

# data point 5 : 17.18 ; 1.91
/musr/command construct box water5 25000 25000 9545 wangpuWater -150000 0 -9545 log_World norot dead 7005
/musr/command construct box tidal5 25000 25000 79 G4_AIR 0 0 9466 log_water5 norot dead 6005
/musr/command construct box mud5 25000 25000 955 GrayMealySand 0 0 -8590 log_water5 norot dead 8005
/musr/command construct box wall5 25000 25000 1000 Concrete -150000 0 -20090 log_World norot dead 5005
/musr/command construct box save_SciDet51 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -150000 0 -27100 log_World norot musr/ScintSD 109
/musr/command construct box save_SciDet52 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -150000 0 -27220 log_World norot musr/ScintSD 110

# data point 6 : 13.22 ; 5.61
/musr/command construct box water6 25000 25000 9415 wangpuWater -100000 0 -9415 log_World norot dead 7006
/musr/command construct box tidal6 25000 25000 79 G4_AIR 0 0 9336 log_water6 norot dead 6006
/musr/command construct box mud6 25000 25000 2805 GrayMealySand 0 0 -6610 log_water6 norot dead 8006
/musr/command construct box wall6 25000 25000 1000 Concrete -100000 0 -19830 log_World norot dead 5006
/musr/command construct box save_SciDet61 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -100000 0 -26840 log_World norot musr/ScintSD 111
/musr/command construct box save_SciDet62 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -100000 0 -26960 log_World norot musr/ScintSD 112

# data point 7 : 9.88 ; 8.68
/musr/command construct box water7 25000 25000 9280 wangpuWater -50000 0 -9280 log_World norot dead 7007
/musr/command construct box tidal7 25000 25000 79 G4_AIR 0 0 9201 log_water7 norot dead 6007
/musr/command construct box mud7 25000 25000 4340 GrayMealySand 0 0 -4940 log_water7 norot dead 8007
/musr/command construct box wall7 25000 25000 1000 Concrete -50000 0 -19560 log_World norot dead 5007
/musr/command construct box save_SciDet71 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -50000 0 -26570 log_World norot musr/ScintSD 113
/musr/command construct box save_SciDet72 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE -50000 0 -26690 log_World norot musr/ScintSD 114

# data point 8 : 10.0 ; 7.21
/musr/command construct box water8 25000 25000 8605 wangpuWater 0 0 -8605 log_World norot dead 7008
/musr/command construct box tidal8 25000 25000 79 G4_AIR 0 0 8526 log_water8 norot dead 6008
/musr/command construct box mud8 25000 25000 3605 GrayMealySand 0 0 -5000 log_water8 norot dead 8008
/musr/command construct box wall8 25000 25000 1000 Concrete 0 0 -18210 log_World norot dead 5008
/musr/command construct box save_SciDet81 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -25220 log_World norot musr/ScintSD 115
/musr/command construct box save_SciDet82 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -25340 log_World norot musr/ScintSD 116

# data point 9 : 2.47 ; 12.98
/musr/command construct box water9 25000 25000 7725 wangpuWater 50000 0 -7725 log_World norot dead 7009
/musr/command construct box tidal9 25000 25000 79 G4_AIR 0 0 7646 log_water9 norot dead 6009
/musr/command construct box mud9 25000 25000 6400 GrayMealySand 0 0 -1325 log_water9 norot dead 8009
/musr/command construct box wall9 25000 25000 1000 Concrete 50000 0 -16450 log_World norot dead 5009
/musr/command construct box save_SciDet91 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 50000 0 -23460 log_World norot musr/ScintSD 117
/musr/command construct box save_SciDet92 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 50000 0 -23580 log_World norot musr/ScintSD 118

################## (full thickness - offset)
# data point 10 : 0 ; 13.54 (0.0014)
/musr/command construct box mud10 25000 25000 6770 GrayMealySand 100000 0 -6768 log_World norot dead 8010
/musr/command construct box wall10 25000 25000 1000 Concrete 100000 0 -14539 log_World norot dead 5010
/musr/command construct box save_SciDet101 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 100000 0 -23544 log_World norot musr/ScintSD 119
/musr/command construct box save_SciDet102 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 100000 0 -23664 log_World norot musr/ScintSD 120

# data point 11 : 0 ; 13.04 +(1.5) 
/musr/command construct box mud11 25000 25000 6520 GrayMealySand 150000 0 -5020 log_World norot dead 8011
/musr/command construct box wall11 25000 25000 1000 Concrete 150000 0 -12540 log_World norot dead 5011
/musr/command construct box save_SciDet111 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 150000 0 -19545 log_World norot musr/ScintSD 121
/musr/command construct box save_SciDet112 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 150000 0 -19665 log_World norot musr/ScintSD 122

# data point 12 : 0 ; 12.21 (2.67)
/musr/command construct box mud12 25000 25000 6105 GrayMealySand 200000 0 -3435 log_World norot dead 8012
/musr/command construct box wall12 25000 25000 1000 Concrete 200000 0 -10540 log_World norot dead 5012
/musr/command construct box save_SciDet121 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 200000 0 -17545 log_World norot musr/ScintSD 123
/musr/command construct box save_SciDet122 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 200000 0 -17665 log_World norot musr/ScintSD 124

# data point 13 : 0 ; 10.69 (3.15)
/musr/command construct box mud13 25000 25000 5345 GrayMealySand 250000 0 -2195 log_World norot dead 8013
/musr/command construct box wall13 25000 25000 1000 Concrete 250000 0 -8540 log_World norot dead 5013
/musr/command construct box save_SciDet131 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 250000 0 -15545 log_World norot musr/ScintSD 125
/musr/command construct box save_SciDet132 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 250000 0 -15665 log_World norot musr/ScintSD 126

# data point 14 : 0 ; 9.30 (3.76)
/musr/command construct box mud14 25000 25000 4650 GrayMealySand 300000 0 -890 log_World norot dead 8014
/musr/command construct box wall14 25000 25000 1000 Concrete 300000 0 -6540 log_World norot dead 5014
/musr/command construct box save_SciDet141 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 300000 0 -13545 log_World norot musr/ScintSD 127
/musr/command construct box save_SciDet142 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 300000 0 -13665 log_World norot musr/ScintSD 128

# data point 15 ; (blank)
##/musr/command construct box mud15 25000 25000 6450 GrayMealySand 350000 0 0 log_World norot dead 8015
#/musr/command construct box wall15 25000 25000 1000 Concrete 350000 0 -20620 log_World norot dead 5015
#/musr/command construct box save_SciDet151 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 350000 0 -28625 log_World norot musr/ScintSD 129
#/musr/command construct box save_SciDet152 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 350000 0 -28745 log_World norot musr/ScintSD 130

# COLORS
/musr/command visattributes log_World invisible
/musr/command visattributes wangpuWater blue
/musr/command visattributes GrayMealySand green
/musr/command visattributes Concrete black
/musr/command visattributes G4_PLASTIC_SC_VINYLTOLUENE oxsteel

#########################  P H Y S I C S      P R O C E S S E S  ##################

/musr/command process addDiscreteProcess gamma G4PhotoElectricEffect
/musr/command process addDiscreteProcess gamma G4ComptonScattering
/musr/command process addDiscreteProcess gamma G4GammaConversion
/musr/command process addDiscreteProcess gamma G4RayleighScattering
/musr/command process addProcess         e-    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e-    G4eIonisation            -1  2  2
/musr/command process addProcess         e-    G4eBremsstrahlung        -1  3  3
/musr/command process addProcess         e+    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e+    G4eIonisation            -1  2  2
/musr/command process addProcess         e+    G4eBremsstrahlung        -1  3  3
/musr/command process addProcess         e+    G4eplusAnnihilation       0 -1  4
/musr/command process addProcess         mu-   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu-   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu-   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu-   G4MuPairProduction       -1  4  4
/musr/command process addProcess         mu+   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu+   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu+   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu+   G4MuPairProduction       -1  4  4

##################  S O M E   O T H E R    P A R A M E T E R S   ##################

# Set the minimum time separation between two subsequent signals in the same detector (in ns)
/musr/command signalSeparationTime 50
/musr/run/howOftenToPrintEvent 1000

# random seed option
/musr/run/randomOption 1

# VISUALISATION
#/control/execute visVRML.mac

/musr/command storeOnlyEventsWithHits true

#########################   R O O T     O U T P U T  ##############################

#/musr/command rootOutput runID off
#/musr/command rootOutput eventID off
/musr/command rootOutput weight off
/musr/command rootOutput BFieldAtDecay off
#/musr/command rootOutput muIniPosX off
#/musr/command rootOutput muIniPosY off
#/musr/command rootOutput muIniPosZ off
#/musr/command rootOutput muIniMomX off
#/musr/command rootOutput muIniMomY off
#/musr/command rootOutput muIniMomZ off
/musr/command rootOutput muIniPolX off
/musr/command rootOutput muIniPolY off
/musr/command rootOutput muIniPolZ off
#/musr/command rootOutput muIniTime off
#/musr/command rootOutput parIniPosX off
#/musr/command rootOutput parIniPosY off
#/musr/command rootOutput parIniPosZ off
#/musr/command rootOutput parIniMomX off
#/musr/command rootOutput parIniMomY off
#/musr/command rootOutput parIniMomZ off
#/musr/command rootOutput parIniTime off
#/musr/command rootOutput parID off
/musr/command rootOutput muDecayDetID off
/musr/command rootOutput muDecayPosX off
/musr/command rootOutput muDecayPosY off
/musr/command rootOutput muDecayPosZ off
/musr/command rootOutput muDecayTime off
/musr/command rootOutput muDecayPolX off
/musr/command rootOutput muDecayPolY off
/musr/command rootOutput muDecayPolZ off
/musr/command rootOutput muTargetTime off
/musr/command rootOutput muTargetPolX off
/musr/command rootOutput muTargetPolY off
/musr/command rootOutput muTargetPolZ off
/musr/command rootOutput muM0Time off
/musr/command rootOutput muM0PolX off
/musr/command rootOutput muM0PolY off
/musr/command rootOutput muM0PolZ off
/musr/command rootOutput muM1Time off
/musr/command rootOutput muM1PolX off
/musr/command rootOutput muM1PolY off
/musr/command rootOutput muM1PolZ off
/musr/command rootOutput muM2Time off
/musr/command rootOutput muM2PolX off
/musr/command rootOutput muM2PolY off
/musr/command rootOutput muM2PolZ off
/musr/command rootOutput posIniMomX off
/musr/command rootOutput posIniMomY off
/musr/command rootOutput posIniMomZ off
/musr/command rootOutput fieldNomVal off
#/musr/command rootOutput det_ID off
#/musr/command rootOutput det_edep off
#/musr/command rootOutput det_edep_el off
#/musr/command rootOutput det_edep_pos off
#/musr/command rootOutput det_edep_gam off
#/musr/command rootOutput det_edep_mup off
#/musr/command rootOutput det_nsteps off
#/musr/command rootOutput det_length off
#/musr/command rootOutput det_start off
#/musr/command rootOutput det_end off
#/musr/command rootOutput det_x off
#/musr/command rootOutput det_y off
#/musr/command rootOutput det_z off
#/musr/command rootOutput det_kine off
/musr/command rootOutput det_VrtxKine off
/musr/command rootOutput det_VrtxX off
/musr/command rootOutput det_VrtxY off
/musr/command rootOutput det_VrtxZ off
/musr/command rootOutput det_VrtxVolID off
/musr/command rootOutput det_VrtxProcID off
/musr/command rootOutput det_VrtxTrackID off
/musr/command rootOutput det_VrtxParticleID off
/musr/command rootOutput det_VvvKine off
/musr/command rootOutput det_VvvX off
/musr/command rootOutput det_VvvY off
/musr/command rootOutput det_VvvZ off
/musr/command rootOutput det_VvvVolID off
/musr/command rootOutput det_VvvProcID off
/musr/command rootOutput det_VvvTrackID off
/musr/command rootOutput det_VvvParticleID off
/musr/command rootOutput odet_ID           off
/musr/command rootOutput nOptPhot          off
/musr/command rootOutput odet_nPhot        off
/musr/command rootOutput odet_timeFirst    off
/musr/command rootOutput odet_timeA        off
/musr/command rootOutput odet_timeB        off
/musr/command rootOutput odet_timeC        off
/musr/command rootOutput odet_timeD        off
/musr/command rootOutput odet_timeE        off
/musr/command rootOutput odet_timeMean     off
/musr/command rootOutput odet_timeLast     off
/musr/command rootOutput odet_timeCFD      off
/musr/command rootOutput odet_amplCFD      off
### Root variables that are not written out by default, but can be switched on:
#/musr/command rootOutput fieldIntegralBx on
#/musr/command rootOutput fieldIntegralBy on
#/musr/command rootOutput fieldIntegralBz on
#/musr/command rootOutput fieldIntegralBz1 on
#/musr/command rootOutput fieldIntegralBz2 on
#/musr/command rootOutput fieldIntegralBz3 on

######################### P A R T I C L E   G U N #################################

# version 1 cosmic muon by Meng Lv
/gun/cosmic_v1 false

# or you can set parameters from input file
#/gun/cry/file CRYSetup.file

# if using CRY or EcoMug, then don't need to set the beam's vertex and direction
#/gun/primaryparticle mu+
#/gun/momentum 6000 MeV
#/gun/vertex 0 0 10000 mm
#/gun/vertexsigma -2500 -500 0 mm
#/gun/direction 0 0 -1

# using CRY
# CRY setup
#/gun/cry/useCRY true
#/gun/cry/input returnMuons 1
#/gun/cry/input returnNeutrons 0
#/gun/cry/input returnProtons 0
#/gun/cry/input returnGammas 0
#/gun/cry/input returnElectrons 0
#/gun/cry/input returnPions 0

# m-d-y
#/gun/cry/input date 7-1-2012
#/gun/cry/input latitude 31.0
#/gun/cry/input altitude 0 # 0 for sea-level
#/gun/cry/input subboxLength 250 # 300 m
#/gun/cry/update

# EcoMug
/gun/ecomug/useEcoMug true
# plane shape: x, y, center(x, y, z) in (mm)
/gun/ecomug/shapeConstruct plane 800000 50000 -25000 0 15000

# sphere shape: only need the size of radius, so set the second number as 0
#/gun/ecomug/shapeConstruct sphere 5000 0 0 0 0

# cylinder shape: radius, height in (mm)
#/gun/ecomug/shapeConstruct cylinder 3000 10000 0 0 0

# you can specify the cosmic muon's momentum range (MeV) and angular range (degree)
#/gun/ecomug/constraints 10 10000 20 60 0 180
#/gun/ecomug/constraints 10 10000 -70 70 -70 70
#/gun/ecomug/constraints 10 10000 -30 30 0 360
#/gun/ecomug/constraints 4000 1000000 0 90 0 360

########################  B E A M    O N  #######################################

# 5 million
#/run/beamOn 5000000
# 1 million
#/run/beamOn 1000000
# 500k
#/run/beamOn 500000
# 425k
#/run/beamOn 425000
# 2300k
/run/beamOn 2300000