#-----------------------------------------------------------------------
# Macro file cosmic muon distribution from CRY
#-----------------------------------------------------------------------

#############################  G E O M E T R Y  ###################################
# WORLD
/musr/command construct box World 17100 9500 7000 G4_AIR 0 0 0 no_logical_volume norot dead -1

#34100 18800

# water 1 m
/musr/command construct box water 950 450 500 G4_WATER 0 0 -3950 log_World norot dead 8000
# 90 cm (450 mm half-thickness):
##/musr/command construct box water 950 450 450 G4_WATER 0 0 -4000 log_World norot dead 8000
# 80 cm (400 mm half-thickness):
##/musr/command construct box water 950 450 400 G4_WATER 0 0 -4050 log_World norot dead 8000
# 70 cm (350 mm half-thickness):
##/musr/command construct box water 950 450 350 G4_WATER 0 0 -4100 log_World norot dead 8000
# 60 cm (300 mm half-thickness):
##/musr/command construct box water 950 450 300 G4_WATER 0 0 -4150 log_World norot dead 8000
# 50 cm (250 mm half-thickness):
##/musr/command construct box water 950 450 250 G4_WATER 0 0 -4200 log_World norot dead 8000
# 40 cm (200 mm half-thickness):
##/musr/command construct box water 950 450 200 G4_WATER 0 0 -4250 log_World norot dead 8000
# 30 cm (150 mm half-thickness):
##/musr/command construct box water 950 450 150 G4_WATER 0 0 -4300 log_World norot dead 8000
# 20 cm (100 mm half-thickness):
##/musr/command construct box water 950 450 100 G4_WATER 0 0 -4350 log_World norot dead 8000
# 10 cm (50 mm half-thickness):
##/musr/command construct box water 950 450 50 G4_WATER 0 0 -4400 log_World norot dead 8000

# Acrylic box
/musr/command construct box Acrylic_box1 25 500 750 Acrylic -975 0 -3750 log_World norot dead 2001
/musr/command construct box Acrylic_box2 25 500 750 Acrylic 975 0 -3750 log_World norot dead 2002
/musr/command construct box Acrylic_box3 950 25 750 Acrylic 0 -475 -3750 log_World norot dead 2003
/musr/command construct box Acrylic_box4 950 25 750 Acrylic 0 475 -3750 log_World norot dead 2004
/musr/command construct box Acrylic_box5 950 450 25 Acrylic 0 0 -4475 log_World norot dead 2005

# sediment # mud thickness 1 meter
#/musr/command construct box mud_1 5000 500 1000 Mud 0 0 -9000 log_water norot dead 1001
#/musr/command construct box mud_2 5000 500 1000 Mud 0 0 -8000 log_water norot dead 1002
#/musr/command construct box mud_3 5000 500 1000 Mud 0 0 -7000 log_water norot dead 1003
#/musr/command construct box mud_4 5000 500 1000 Mud 0 0 -6000 log_water norot dead 1004
#/musr/command construct box mud_5 5000 500 1000 Mud 0 0 -5000 log_water norot dead 1005
#/musr/command construct box mud_6 5000 500 1000 Mud 0 0 -4000 log_water norot dead 1006
#/musr/command construct box mud_7 5000 500 1000 Mud 0 0 -3000 log_water norot dead 1007
#/musr/command construct box mud_8 5000 500 1000 Mud 0 0 -2000 log_water norot dead 1008
#/musr/command construct box mud_9 5000 500 1000 Mud 0 0 -1000 log_water norot dead 1009

# detector
/musr/command construct box save_SciDet6 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -4970 log_World norot musr/ScintSD 101
/musr/command construct box save_SciDet7 400 100 10 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -5090 log_World norot musr/ScintSD 102

# COLORS
/musr/command visattributes log_World invisible
/musr/command visattributes G4_PLASTIC_SC_VINYLTOLUENE red
/musr/command visattributes log_water lightblue
/musr/command visattributes log_mud1 black
/musr/command visattributes log_mud2 black
/musr/command visattributes log_mud3 black
/musr/command visattributes log_mud4 black
/musr/command visattributes log_mud5 black
/musr/command visattributes log_E1 green
/musr/command visattributes log_floor black
/musr/command visattributes Acrylic white

#########################  P H Y S I C S      P R O C E S S E S  ##################

/musr/command process addDiscreteProcess gamma G4PhotoElectricEffect
/musr/command process addDiscreteProcess gamma G4ComptonScattering
/musr/command process addDiscreteProcess gamma G4GammaConversion
/musr/command process addDiscreteProcess gamma G4RayleighScattering
/musr/command process addProcess         e-    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e-    G4eIonisation            -1  2  2
/musr/command process addProcess         e-    G4eBremsstrahlung        -1  3  3
/musr/command process addProcess         e+    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e+    G4eIonisation            -1  2  2
/musr/command process addProcess         e+    G4eBremsstrahlung        -1  3  3
/musr/command process addProcess         e+    G4eplusAnnihilation       0 -1  4
/musr/command process addProcess         mu-   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu-   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu-   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu-   G4MuPairProduction       -1  4  4
/musr/command process addProcess         mu+   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu+   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu+   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu+   G4MuPairProduction       -1  4  4

##################  S O M E   O T H E R    P A R A M E T E R S   ##################

# Set the minimum time separation between two subsequent signals in the same detector (in ns)
/musr/command signalSeparationTime 50
/musr/run/howOftenToPrintEvent 1000

# random seed option
/musr/run/randomOption 1

########################## V I S U A L I S A T I O N ##############################


#/vis/disable
##/control/execute visVRML.mac

/musr/command storeOnlyEventsWithHits false

#########################   R O O T     O U T P U T  ##############################

#/musr/command rootOutput runID off
#/musr/command rootOutput eventID off
/musr/command rootOutput weight off
/musr/command rootOutput BFieldAtDecay off
#/musr/command rootOutput muIniPosX off
#/musr/command rootOutput muIniPosY off
#/musr/command rootOutput muIniPosZ off
#/musr/command rootOutput muIniMomX off
#/musr/command rootOutput muIniMomY off
#/musr/command rootOutput muIniMomZ off
/musr/command rootOutput muIniPolX off
/musr/command rootOutput muIniPolY off
/musr/command rootOutput muIniPolZ off
#/musr/command rootOutput muIniTime off
#/musr/command rootOutput parIniPosX off
#/musr/command rootOutput parIniPosY off
#/musr/command rootOutput parIniPosZ off
#/musr/command rootOutput parIniMomX off
#/musr/command rootOutput parIniMomY off
#/musr/command rootOutput parIniMomZ off
#/musr/command rootOutput parIniTime off
#/musr/command rootOutput parID off
/musr/command rootOutput muDecayDetID off
/musr/command rootOutput muDecayPosX off
/musr/command rootOutput muDecayPosY off
/musr/command rootOutput muDecayPosZ off
/musr/command rootOutput muDecayTime off
/musr/command rootOutput muDecayPolX off
/musr/command rootOutput muDecayPolY off
/musr/command rootOutput muDecayPolZ off
/musr/command rootOutput muTargetTime off
/musr/command rootOutput muTargetPolX off
/musr/command rootOutput muTargetPolY off
/musr/command rootOutput muTargetPolZ off
/musr/command rootOutput muM0Time off
/musr/command rootOutput muM0PolX off
/musr/command rootOutput muM0PolY off
/musr/command rootOutput muM0PolZ off
/musr/command rootOutput muM1Time off
/musr/command rootOutput muM1PolX off
/musr/command rootOutput muM1PolY off
/musr/command rootOutput muM1PolZ off
/musr/command rootOutput muM2Time off
/musr/command rootOutput muM2PolX off
/musr/command rootOutput muM2PolY off
/musr/command rootOutput muM2PolZ off
/musr/command rootOutput posIniMomX off
/musr/command rootOutput posIniMomY off
/musr/command rootOutput posIniMomZ off
/musr/command rootOutput fieldNomVal off
#/musr/command rootOutput det_ID off
#/musr/command rootOutput det_edep off
#/musr/command rootOutput det_edep_el off
#/musr/command rootOutput det_edep_pos off
#/musr/command rootOutput det_edep_gam off
#/musr/command rootOutput det_edep_mup off
#/musr/command rootOutput det_nsteps off
#/musr/command rootOutput det_length off
#/musr/command rootOutput det_start off
#/musr/command rootOutput det_end off
#/musr/command rootOutput det_x off
#/musr/command rootOutput det_y off
#/musr/command rootOutput det_z off
#/musr/command rootOutput det_kine off
/musr/command rootOutput det_VrtxKine off
/musr/command rootOutput det_VrtxX off
/musr/command rootOutput det_VrtxY off
/musr/command rootOutput det_VrtxZ off
/musr/command rootOutput det_VrtxVolID off
/musr/command rootOutput det_VrtxProcID off
#/musr/command rootOutput det_VrtxTrackID off
#/musr/command rootOutput det_VrtxParticleID off
/musr/command rootOutput det_VvvKine off
/musr/command rootOutput det_VvvX off
/musr/command rootOutput det_VvvY off
/musr/command rootOutput det_VvvZ off
/musr/command rootOutput det_VvvVolID off
/musr/command rootOutput det_VvvProcID off
/musr/command rootOutput det_VvvTrackID off
/musr/command rootOutput det_VvvParticleID off
/musr/command rootOutput odet_ID           off
/musr/command rootOutput nOptPhot          off
/musr/command rootOutput odet_nPhot        off
/musr/command rootOutput odet_timeFirst    off
/musr/command rootOutput odet_timeA        off
/musr/command rootOutput odet_timeB        off
/musr/command rootOutput odet_timeC        off
/musr/command rootOutput odet_timeD        off
/musr/command rootOutput odet_timeE        off
/musr/command rootOutput odet_timeMean     off
/musr/command rootOutput odet_timeLast     off
/musr/command rootOutput odet_timeCFD      off
/musr/command rootOutput odet_amplCFD      off
### Root variables that are not written out by default, but can be switched on:
#/musr/command rootOutput fieldIntegralBx on
#/musr/command rootOutput fieldIntegralBy on
#/musr/command rootOutput fieldIntegralBz on
#/musr/command rootOutput fieldIntegralBz1 on
#/musr/command rootOutput fieldIntegralBz2 on
#/musr/command rootOutput fieldIntegralBz3 on

######################### P A R T I C L E   G U N #################################

# version 1 cosmic muon by Meng Lv
/gun/cosmic_v1 false

# or you can set parameters from input file
#/gun/cry/file CRYSetup.file

# if using CRY or EcoMug, then don't need to set the beam's vertex and direction
#/gun/primaryparticle mu+
#/gun/momentum 6000 MeV
#/gun/vertex 0 0 10000 mm
#/gun/vertexsigma -2500 -500 0 mm
#/gun/direction 0 0 -1

# using CRY
# CRY setup
#/gun/cry/useCRY true
#/gun/cry/input returnMuons 1
#/gun/cry/input returnNeutrons 0
#/gun/cry/input returnProtons 0
#/gun/cry/input returnGammas 0
#/gun/cry/input returnElectrons 0
#/gun/cry/input returnPions 0

# m-d-y
#/gun/cry/input date 7-1-2012
#/gun/cry/input latitude 31.0
#/gun/cry/input altitude 0 # 0 for sea-level
#/gun/cry/input subboxLength 130 # 130 m
#/gun/cry/update

# EcoMug
/gun/ecomug/useEcoMug true
##/gun/ecomug/shapeConstruct plane 68200 20000 0 0 -2300
/gun/ecomug/shapeConstruct plane 34100 18800 0 0 0


########################  B E A M    O N  #######################################

/run/beamOn 2000000
#2000000
#200000000