#-----------------------------------------------------------------------
# Macro file cosmic muon distribution from CRY
#-----------------------------------------------------------------------

#############################  G E O M E T R Y  ###################################
# WORLD
/musr/command construct box World 50000 50000 50000 G4_AIR 0 0 0 no_logical_volume norot dead -1

# Note, shower always start at z = 0

# 10 meter above : half length : 10000 + 2500
# each density block is 10 meter
/musr/command construct box water 5000 5000 5000 G4_WATER -15000 15000 -15000 log_World norot dead 8000
/musr/command construct box mud 5000 5000 5000 Mud 15000 15000 -15000 log_World norot dead 8001
/musr/command construct box rock 5000 5000 5000 Rock -15000 -15000 -15000 log_World norot dead 8002
/musr/command construct box concrete 5000 5000 5000 Concrete 15000 -15000 -15000 log_World norot dead 8003

# water
/musr/command construct box save_SciDet1 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 5000 log_water norot musr/ScintSD 100
/musr/command construct box save_SciDet2 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 3000 log_water norot musr/ScintSD 101
/musr/command construct box save_SciDet3 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 1000 log_water norot musr/ScintSD 102
/musr/command construct box save_SciDet4 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -1000 log_water norot musr/ScintSD 103
/musr/command construct box save_SciDet5 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -3000 log_water norot musr/ScintSD 104
/musr/command construct box save_SciDet6 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -5000 log_water norot musr/ScintSD 105

# mud
/musr/command construct box save_SciDet7 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 5000 log_mud norot musr/ScintSD 200
/musr/command construct box save_SciDet8 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 3000 log_mud norot musr/ScintSD 201
/musr/command construct box save_SciDet9 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 1000 log_mud norot musr/ScintSD 202
/musr/command construct box save_SciDet10 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -1000 log_mud norot musr/ScintSD 203
/musr/command construct box save_SciDet11 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -3000 log_mud norot musr/ScintSD 204
/musr/command construct box save_SciDet12 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -5000 log_mud norot musr/ScintSD 205

# rock
/musr/command construct box save_SciDet13 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 5000 log_rock norot musr/ScintSD 300
/musr/command construct box save_SciDet14 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 3000 log_rock norot musr/ScintSD 301
/musr/command construct box save_SciDet15 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 1000 log_rock norot musr/ScintSD 302
/musr/command construct box save_SciDet16 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -1000 log_rock norot musr/ScintSD 303
/musr/command construct box save_SciDet17 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -3000 log_rock norot musr/ScintSD 304
/musr/command construct box save_SciDet18 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -5000 log_rock norot musr/ScintSD 305

# concrete
/musr/command construct box save_SciDet19 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 5000 log_concrete norot musr/ScintSD 400
/musr/command construct box save_SciDet20 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 3000 log_concrete norot musr/ScintSD 401
/musr/command construct box save_SciDet21 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 1000 log_concrete norot musr/ScintSD 402
/musr/command construct box save_SciDet22 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -1000 log_concrete norot musr/ScintSD 403
/musr/command construct box save_SciDet23 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -3000 log_concrete norot musr/ScintSD 404
/musr/command construct box save_SciDet24 5000 5000 5 G4_PLASTIC_SC_VINYLTOLUENE 0 0 -5000 log_concrete norot musr/ScintSD 405

# COLORS
/musr/command visattributes log_World invisible
/musr/command visattributes G4_PLASTIC_SC_VINYLTOLUENE red
/musr/command visattributes log_water lightblue
/musr/command visattributes log_mud black
/musr/command visattributes log_rock gray
/musr/command visattributes log_concrete darkblue

#########################  P H Y S I C S      P R O C E S S E S  ##################

/musr/command process addDiscreteProcess gamma G4PhotoElectricEffect
/musr/command process addDiscreteProcess gamma G4ComptonScattering
/musr/command process addDiscreteProcess gamma G4GammaConversion
/musr/command process addDiscreteProcess gamma G4RayleighScattering
/musr/command process addProcess         e-    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e-    G4eIonisation            -1  2  2
/musr/command process addProcess         e-    G4eBremsstrahlung        -1  3  3
/musr/command process addProcess         e+    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e+    G4eIonisation            -1  2  2
/musr/command process addProcess         e+    G4eBremsstrahlung        -1  3  3
/musr/command process addProcess         e+    G4eplusAnnihilation       0 -1  4
/musr/command process addProcess         mu-   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu-   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu-   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu-   G4MuPairProduction       -1  4  4
/musr/command process addProcess         mu+   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu+   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu+   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu+   G4MuPairProduction       -1  4  4

##################  S O M E   O T H E R    P A R A M E T E R S   ##################

# Set the minimum time separation between two subsequent signals in the same detector (in ns)
/musr/command signalSeparationTime 50
/musr/run/howOftenToPrintEvent 1000

# random seed option
/musr/run/randomOption 1

# VISUALISATION
#/control/execute visVRML.mac

/musr/command storeOnlyEventsWithHits false

#########################   R O O T     O U T P U T  ##############################

#/musr/command rootOutput runID off
#/musr/command rootOutput eventID off
/musr/command rootOutput weight off
/musr/command rootOutput BFieldAtDecay off
#/musr/command rootOutput muIniPosX off
#/musr/command rootOutput muIniPosY off
#/musr/command rootOutput muIniPosZ off
#/musr/command rootOutput muIniMomX off
#/musr/command rootOutput muIniMomY off
#/musr/command rootOutput muIniMomZ off
/musr/command rootOutput muIniPolX off
/musr/command rootOutput muIniPolY off
/musr/command rootOutput muIniPolZ off
#/musr/command rootOutput muIniTime off
#/musr/command rootOutput parIniPosX off
#/musr/command rootOutput parIniPosY off
#/musr/command rootOutput parIniPosZ off
#/musr/command rootOutput parIniMomX off
#/musr/command rootOutput parIniMomY off
#/musr/command rootOutput parIniMomZ off
#/musr/command rootOutput parIniTime off
#/musr/command rootOutput parID off
/musr/command rootOutput muDecayDetID off
/musr/command rootOutput muDecayPosX off
/musr/command rootOutput muDecayPosY off
/musr/command rootOutput muDecayPosZ off
/musr/command rootOutput muDecayTime off
/musr/command rootOutput muDecayPolX off
/musr/command rootOutput muDecayPolY off
/musr/command rootOutput muDecayPolZ off
/musr/command rootOutput muTargetTime off
/musr/command rootOutput muTargetPolX off
/musr/command rootOutput muTargetPolY off
/musr/command rootOutput muTargetPolZ off
/musr/command rootOutput muM0Time off
/musr/command rootOutput muM0PolX off
/musr/command rootOutput muM0PolY off
/musr/command rootOutput muM0PolZ off
/musr/command rootOutput muM1Time off
/musr/command rootOutput muM1PolX off
/musr/command rootOutput muM1PolY off
/musr/command rootOutput muM1PolZ off
/musr/command rootOutput muM2Time off
/musr/command rootOutput muM2PolX off
/musr/command rootOutput muM2PolY off
/musr/command rootOutput muM2PolZ off
/musr/command rootOutput posIniMomX off
/musr/command rootOutput posIniMomY off
/musr/command rootOutput posIniMomZ off
/musr/command rootOutput fieldNomVal off
#/musr/command rootOutput det_ID off
#/musr/command rootOutput det_edep off
#/musr/command rootOutput det_edep_el off
#/musr/command rootOutput det_edep_pos off
#/musr/command rootOutput det_edep_gam off
#/musr/command rootOutput det_edep_mup off
#/musr/command rootOutput det_nsteps off
#/musr/command rootOutput det_length off
#/musr/command rootOutput det_start off
#/musr/command rootOutput det_end off
#/musr/command rootOutput det_x off
#/musr/command rootOutput det_y off
#/musr/command rootOutput det_z off
#/musr/command rootOutput det_kine off
/musr/command rootOutput det_VrtxKine off
/musr/command rootOutput det_VrtxX off
/musr/command rootOutput det_VrtxY off
/musr/command rootOutput det_VrtxZ off
/musr/command rootOutput det_VrtxVolID off
/musr/command rootOutput det_VrtxProcID off
/musr/command rootOutput det_VrtxTrackID off
/musr/command rootOutput det_VrtxParticleID off
/musr/command rootOutput det_VvvKine off
/musr/command rootOutput det_VvvX off
/musr/command rootOutput det_VvvY off
/musr/command rootOutput det_VvvZ off
/musr/command rootOutput det_VvvVolID off
/musr/command rootOutput det_VvvProcID off
/musr/command rootOutput det_VvvTrackID off
/musr/command rootOutput det_VvvParticleID off
/musr/command rootOutput odet_ID           off
/musr/command rootOutput nOptPhot          off
/musr/command rootOutput odet_nPhot        off
/musr/command rootOutput odet_timeFirst    off
/musr/command rootOutput odet_timeA        off
/musr/command rootOutput odet_timeB        off
/musr/command rootOutput odet_timeC        off
/musr/command rootOutput odet_timeD        off
/musr/command rootOutput odet_timeE        off
/musr/command rootOutput odet_timeMean     off
/musr/command rootOutput odet_timeLast     off
/musr/command rootOutput odet_timeCFD      off
/musr/command rootOutput odet_amplCFD      off
### Root variables that are not written out by default, but can be switched on:
#/musr/command rootOutput fieldIntegralBx on
#/musr/command rootOutput fieldIntegralBy on
#/musr/command rootOutput fieldIntegralBz on
#/musr/command rootOutput fieldIntegralBz1 on
#/musr/command rootOutput fieldIntegralBz2 on
#/musr/command rootOutput fieldIntegralBz3 on

######################### P A R T I C L E   G U N #################################

# version 1 cosmic muon by Meng Lv
#/gun/cosmic_v1 false

# or you can set parameters from input file
#/gun/cry/file CRYSetup.file

# if using CRY or EcoMug, then don't need to set the beam's vertex and direction
#/gun/primaryparticle mu+
#/gun/momentum 6000 MeV
#/gun/vertex 0 0 10000 mm
#/gun/vertexsigma -2500 -500 0 mm
#/gun/direction 0 0 -1

# using CRY
# CRY setup
/gun/cry/useCRY true
/gun/cry/input returnMuons 1
/gun/cry/input returnNeutrons 0
/gun/cry/input returnProtons 0
/gun/cry/input returnGammas 0
/gun/cry/input returnElectrons 0
/gun/cry/input returnPions 0

# m-d-y
/gun/cry/input date 7-1-2012
/gun/cry/input latitude 31.0
/gun/cry/input altitude 0 # 0 for sea-level
/gun/cry/input subboxLength 50 # max 300 m
/gun/cry/update

########################  B E A M    O N  #######################################

# 5 million
#/run/beamOn 5000000
# 1 million
#/run/beamOn 1000000
# 0.2 million
/run/beamOn 200000
#/run/beamOn 100
